[package]
name = "shotgun_gameserver"
version = "0.1.0"
authors = ["Stefan Schindler <stefan@estada.ch>"]

[dependencies]
shotgun_common = { path = "../shotgun_common" }
docopt = "^0.7"
rustc-serialize = "^0.3"

tokio-proto = "0.1"
