[package]
name = "shotgun_coward_bot"
version = "0.1.0"
authors = ["Stefan Schindler <dns2utf8@estada.ch>"]

[dependencies]
shotgun_common = { path = "../shotgun_common" }
docopt = "^0.7"
rustc-serialize = "^0.3"
